class Autogenerated {
  List<PaymentMethods>? paymentMethodsList = [];

  Autogenerated({this.paymentMethodsList});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    json['payment_methods'] != null
        ? json['payment_methods'].entries.forEach(
            (e) => paymentMethodsList!.add(PaymentMethods.fromJson(e.value)))
        : null;
  }
}

class PaymentMethods {
  String? code;
  String? title;
  String? terms;
  String? sortOrder;

  PaymentMethods({this.code, this.title, this.terms, this.sortOrder});

  PaymentMethods.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    title = json['title'];
    terms = json['terms'];
    sortOrder = json['sort_order'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['title'] = this.title;
    data['terms'] = this.terms;
    data['sort_order'] = this.sortOrder;
    return data;
  }
}
