/// Generated by AssetsRefGenerator on 2022/12/18
class Res {
  static const String ama = "assets/ama.jpg";
  static const String baby = "assets/baby.png";
  static const String bag = "assets/bag.png";
  static const String beauty = "assets/beauty.png";
  static const String camera = "assets/camera.png";
  static const String cod = "assets/cod.png";
  static const String cr7 = "assets/cr7.jpg";
  static const String food = "assets/food.png";
  static const String fs = "assets/fs.png";
  static const String google = "assets/google.svg";
  static const String grocery = "assets/grocery.png";
  static const String health = "assets/health.png";
  static const String help = "assets/help.png";
  static const String hf = "assets/hf.png";
  static const String home = "assets/home.png";
  static const String ic_home = "assets/ic_home.png";
  static const String ic_pincode = "assets/ic_pincode.png";
  static const String icon = "assets/icon.png";
  static const String location = "assets/location.png";
  static const String login = "assets/login.png";
  static const String logo = "assets/logo.png";
  // static const String logo = "assets/logo.svg";
  static const String logo_white = "assets/logo-white.png";
  static const String mark = "assets/mark.png";
  static const String master = "assets/master.png";
  static const String no = "assets/no.png";
  static const String noo = "assets/noo.png";
  static const String repeate_icon = "assets/repeate_icon.png";
  static const String sell = "assets/sell.png";
  static const String shirt = "assets/shirt.png";
  static const String shoes = "assets/shoes.png";
  static const String start = "assets/start.png";
  static const String tick = "assets/tick.png";
  static const String visa = "assets/visa.jpg";
}
